name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_ui_auth: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get: ^4.7.3
  intl: ^0.20.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
